name: "Packaging"
description: "Shared Packaging"

runs:
  using: "composite"
  steps:
    - name: Download Workflow Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: List Downloaded Artifacts
      run: |
        echo "Downloaded Artifacts:"
        ls -R artifacts
      shell: bash
