name: "Packaging"
description: "Shared Packaging"

runs:
  using: "composite"
  steps:
    - name: Download Workflow Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: List Downloaded Artifacts
      run: ls -R artifacts
      shell: bash

    - name: Save Package
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: artifacts/
