name: 🔒 Reusable Shared Package
on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Create Package
        id: packaging
        uses: ./.github/actions/Shared/run-packaging
